### ISSUE TITLE
Temperature anomaly computation for Antarctic SMB

### ISSUE THREAD

**Issue by dlebars** [erwinlambert/codependence#1]
The temperature TA that should be used in the Antactic SMB formula should be anomalous temperature compared to 1986-2005 (including 2005).

I am not sure this is done:
    #Convert to SLR
    SMB = 1923*.051*TA

https://github.com/erwinlambert/codependence/blob/master/code/main_Asmb.ipynb

**Comment by erwinlambert** [comment]
Yeah TA is the temperature anomaly.

The function fun.detrend deals with detrending with respect to PIcontrol 1986-2005.

So this function both detrends the projected curve and references it to this period.

It's also used to reference all SLR curves in case they are not 0 per definition in this period (e.g., Antarctic dynamics)

**Comment by dlebars** [comment]
ok, great!
